### ISSUE TITLE
[bug] when i send link bot brokes.

### ISSUE THREAD

**Issue by kpopdev** [juuyokka/TikTokBot#3]
(node:12232) UnhandledPromiseRejectionWarning: Error: Evaluation failed: TypeError: Cannot read property 'href' of undefined
    at __puppeteer_evaluation_script__:3:38
    at ExecutionContext._evaluateInternal (/root/tiktok/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:217:19)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async ExecutionContext.evaluate (/root/tiktok/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:106:16)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:12232) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:12232) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by kpopdev** [comment]
can you please fix this <3 @juuyokka
